### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/phpstorm#1]
This Package will be removed in 7 days from KCP.

Reason: **Broken**
`==> ERROR: arch should be an array`

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145) and [KCP Guide](https://kaosx.us/kcp-guide/)

**Comment by forostm** [comment]
bug fixed & updated to last stable version
